# Genesis Protocol - Dependabot Configuration
# FULLY AUTOMATED dependency management for consciousness-level builds

version: 2
updates:
  # ===== GRADLE BUILD SYSTEM =====
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "daily"
      time: "04:00"
      timezone: "UTC"
    target-branch: "main"
    open-pull-requests-limit: 10
    commit-message:
      prefix: "deps(gradle):"
      include: "scope"
    labels:
      - "dependencies"
      - "gradle"
      - "auto-update"
      - "genesis-protocol"
    # Group related updates
    groups:
      # Android Core Group
      android-core:
        patterns:
          - "com.android.*"
          - "androidx.*"
        update-types:
          - "minor"
          - "patch"
      
      # Kotlin & Compose Group  
      kotlin-compose:
        patterns:
          - "org.jetbrains.kotlin*"
          - "androidx.compose*"
          - "org.jetbrains.kotlinx*"
        update-types:
          - "minor"
          - "patch"
      
      # Security Group (High Priority)
      security:
        patterns:
          - "*security*"
          - "*crypto*"
          - "*tink*"
          - "*conscrypt*"
          - "*bouncycastle*"
        update-types:
          - "minor"
          - "patch"
      
      # Testing Group
      testing:
        patterns:
          - "*junit*"
          - "*test*"
          - "*espresso*"
          - "*mockk*"
          - "*turbine*"
        update-types:
          - "minor"
          - "patch"
      
      # Networking Group
      networking:
        patterns:
          - "*retrofit*"
          - "*okhttp*"
          - "*moshi*"
          - "*serialization*"
        update-types:
          - "minor"
          - "patch"

  # ===== GITHUB ACTIONS =====
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
      timezone: "UTC"
    target-branch: "main"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "ci:"
      include: "scope"
    labels:
      - "ci"
      - "github-actions"
      - "auto-update"

  # ===== SEPARATE UPDATE FOR MAJOR VERSIONS =====
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "monthly"
      day: "monday"  # <-- corrected from "1"
      time: "04:00"
      timezone: "UTC"
    target-branch: "main"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "deps(major):"
      include: "scope"
    labels:
      - "dependencies"
      - "major-update"
      - "requires-review"
    # Only major version updates
    groups:
      major-updates:
        patterns:
          - "*"
        update-types:
          - "major"      prefix: "deps(major):"
      include: "scope"
    labels:
      - "dependencies"
      - "major-update"
      - "requires-review"
    # Only major version updates
    groups:
      major-updates:
        patterns:
          - "*"
        update-types:
          - "major"
