[versions]
# --- CORE TOOLCHAIN: THE LATEST PUBLIC RELEASES ---
# AGP version is now specified directly in build.gradle.kts
desugar_jdk_libs = "2.1.5"
espressoCoreVersion = "3.5.1"
generativeai = "0.9.0"
junitVersion = "1.1.5"
kotlin = "2.0.0" # Latest stable Kotlin version
ksp = "2.0.0-1.0.21" # KSP version matching Kotlin 2.0.0
hilt = "2.51.1" # Latest stable version compatible with Kotlin 2.0.0
hiltNavigationCompose = "1.2.0"
hiltWork = "1.2.0"

# Compose
composeBom = "2024.01.00" # Latest stable Compose BOM for Kotlin 2.0.0
composeCompiler = "1.5.8" # Compose compiler for Kotlin 2.0.0
material3 = "1.2.1" # Latest stable Material 3 version
material3Adaptive = "1.0.0" # Material 3 Adaptive components
navigationComposeVersion = "2.7.7" # Navigation Compose version compatible with our setup
windowSizeClass = "1.2.1" # Window size class for responsive layouts

googleServices = "4.4.3" # Stable Google Services plugin (keeping this update)

# --- APP Dependencies ---
accompanistPager = "0.36.0" # Needs migration to official Compose Pager
accompanistPermissions = "0.37.3" # Needs migration to official permissions handling
accompanistSystemuicontroller = "0.36.0" # Needs migration (e.g., enableEdgeToEdge)
# AndroidX Core
coreKtx = "1.12.0"
appcompat = "1.6.1"
activityCompose = "1.8.2"
material = "1.11.0"

# Navigation
navigationCompose = "2.7.7"

# Lifecycle
lifecycle = "2.7.0"
lifecycleRuntimeCompose = "2.7.0"
lifecycleViewmodelCompose = "2.7.0"

# Room
room = "2.7.2"

# WorkManager
workManager = "2.9.0"

# DataStore
datastore = "1.0.0"
datastoreCore = "1.0.0"

# Security
securityCrypto = "1.1.0-alpha06"

# Firebase
firebaseBomVersion = "32.7.2"

# Kotlin
kotlinxCoroutines = "1.7.3"
kotlinxSerializationJson = "1.6.0"
kotlinxDatetime = "0.4.1"

# Networking
retrofit = "2.9.0"
okhttp = "5.0.0-alpha.12"

converterGson = "3.0.0" # Align with Retrofit
retrofitKotlinxSerializationConverter = "1.0.0"
coilCompose = "2.7.0"
timber = "5.0.1"
guavaAndroid = "33.4.8-android"

# --- Testing ---
junit = "4.13.2"
androidxTestExtJunit = "1.2.1"
espressoCore = "3.6.1"
mockk = "1.14.4"

# --- Build Logic Plugins ---
openapiGeneratorPlugin = "7.14.0" # Updated to latest stable version

firebaseCrashlyticsPlugin = "3.0.4"
firebasePerfPlugin = "1.4.2"
toolchainsFoojayResolver = "1.0.0"

[libraries]
# Hilt (Core & Testing)
animation = { module = "androidx.compose.animation:animation" }
desugarJdkLibs = { module = "com.android.tools:desugar_jdk_libs", version.ref = "desugar_jdk_libs" }
espressoCoreV351 = { module = "androidx.test.espresso:espresso-core", version = "3.5.1" }
foundation = { module = "androidx.compose.foundation:foundation" }
generativeai = { module = "com.google.ai.client.generativeai:generativeai", version.ref = "generativeai" }
hiltAndroid = { module = "com.google.dagger:hilt-android", version.ref = "hilt" }
hiltCompiler = { module = "com.google.dagger:hilt-compiler", version.ref = "hilt" } # KSP
hiltNavigationCompose = { module = "androidx.hilt:hilt-navigation-compose", version.ref = "hiltNavigationCompose" }
hiltWork = { module = "androidx.hilt:hilt-work", version.ref = "hiltWork" }
hiltAndroidTesting = { module = "com.google.dagger:hilt-android-testing", version.ref = "hilt" }
hiltAndroidCompiler = { module = "com.google.dagger:hilt-android-compiler", version.ref = "hilt" }

# Compose BOM and Libraries (versions from BOM)
composeBom = { group = "androidx.compose", name = "compose-bom", version = "2025.06.01" }
androidxUi = { group = "androidx.compose.ui", name = "ui" }
androidxUiGraphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidxUiToolingPreview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }

# Material 3
androidxMaterial3 = { group = "androidx.compose.material3", name = "material3" }
androidxMaterialIconsExtended = { group = "androidx.compose.material", name = "material-icons-extended" }
androidxComposeAnimation = { group = "androidx.compose.animation", name = "animation" }
# Window Manager for window size classes
androidxWindow = { group = "androidx.window", name = "window", version = "1.4.0" }
composeUiTestJunit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
composeUiTooling = { group = "androidx.compose.ui", name = "ui-tooling" }
composeUiTestManifest = { group = "androidx.compose.ui", name = "ui-test-manifest", version = "1.8.3" }

# AndroidX
androidxCoreKtx = { module = "androidx.core:core-ktx", version.ref = "coreKtx" }
androidxAppcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
androidxActivityCompose = { module = "androidx.activity:activity-compose", version.ref = "activityCompose" }
androidxNavigationCompose = { module = "androidx.navigation:navigation-compose", version.ref = "navigationCompose" }
androidxLifecycleRuntimeKtx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycle" }
androidxLifecycleViewmodelKtx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycle" }
androidxLifecycleLivedataKtx = { module = "androidx.lifecycle:lifecycle-livedata-ktx", version.ref = "lifecycle" }
junitV115 = { module = "androidx.test.ext:junit", version = "1.1.5" }
lifecycleCommonJava8 = { module = "androidx.lifecycle:lifecycle-common-java8", version.ref = "lifecycle" }
androidxLifecycleProcess = { module = "androidx.lifecycle:lifecycle-process", version.ref = "lifecycle" }
androidxLifecycleService = { module = "androidx.lifecycle:lifecycle-service", version.ref = "lifecycle" }
androidxLifecycleRuntimeCompose = { module = "androidx.lifecycle:lifecycle-runtime-compose", version.ref = "lifecycleRuntimeCompose" }
androidxLifecycleViewmodelCompose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "lifecycleViewmodelCompose" }
lifecycleViewmodelCompose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "lifecycleViewmodelCompose" }
androidxRoomRuntime = { module = "androidx.room:room-runtime", version.ref = "room" }
androidxRoomKtx = { module = "androidx.room:room-ktx", version.ref = "room" }
androidxRoomCompiler = { module = "androidx.room:room-compiler", version.ref = "room" }
androidxWorkRuntimeKtx = { module = "androidx.work:work-runtime-ktx", version.ref = "workManager" }
androidxDatastorePreferences = { module = "androidx.datastore:datastore-preferences", version.ref = "datastore" }
androidxDatastoreCore = { module = "androidx.datastore:datastore-core", version.ref = "datastoreCore" }
androidxSecurityCrypto = { module = "androidx.security:security-crypto", version = "1.1.0-beta01" }

# Firebase
firebaseBom = { group = "com.google.firebase", name = "firebase-bom", version.ref = "firebaseBomVersion" }
firebaseAnalyticsKtx = { group = "com.google.firebase", name = "firebase-analytics-ktx", version = "22.5.0" }
firebaseCrashlyticsKtx = { group = "com.google.firebase", name = "firebase-crashlytics-ktx", version = "19.4.4" }
firebasePerfKtx = { group = "com.google.firebase", name = "firebase-perf-ktx", version = "21.0.5" }
firebaseMessagingKtx = { group = "com.google.firebase", name = "firebase-messaging-ktx", version = "24.1.2" }
firebaseConfigKtx = { module = "com.google.firebase:firebase-config-ktx", version = "22.1.2" } # Version will be supplied by BoM
firebaseStorageKtx = { module = "com.google.firebase:firebase-storage-ktx", version = "21.0.2" } # Version will be supplied by BoM

# KotlinX
kotlinxCoroutinesCore = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinxCoroutines" }
kotlinxCoroutinesAndroid = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinxCoroutines" }
kotlinxCoroutinesPlayServices = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-play-services", version.ref = "kotlinxCoroutines" }
kotlinxCoroutinesTest = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinxCoroutines" }
kotlinxSerializationJson = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerializationJson" }
kotlinxDatetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinxDatetime" }

# Network
material = { module = "com.google.android.material:material", version.ref = "material" }
material3 = { module = "androidx.compose.material3:material3" }
navigationCompose = { module = "androidx.navigation:navigation-compose", version.ref = "navigationComposeVersion" }
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
converterGson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "converterGson" }
retrofitKotlinxSerializationConverter = { module = "com.jakewharton.retrofit:retrofit2-kotlinx-serialization-converter", version.ref = "retrofitKotlinxSerializationConverter" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
okhttpLoggingInterceptor = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "okhttp" }

# UI & Utils
coilCompose = { module = "io.coil-kt:coil-compose", version.ref = "coilCompose" }
timber = { module = "com.jakewharton.timber:timber", version.ref = "timber" }
guava = { module = "com.google.guava:guava", version.ref = "guavaAndroid" }
accompanistPager = { module = "com.google.accompanist:accompanist-pager", version.ref = "accompanistPager" }
accompanistPagerIndicators = { module = "com.google.accompanist:accompanist-pager-indicators", version.ref = "accompanistPager" }
accompanistPermissions = { module = "com.google.accompanist:accompanist-permissions", version.ref = "accompanistPermissions" }
accompanistSystemuicontroller = { module = "com.google.accompanist:accompanist-systemuicontroller", version.ref = "accompanistSystemuicontroller" }

# Plugins
[plugins]
# Android
android-application = { id = "com.android.application" }
android-library = { id = "com.android.library" }

# Kotlin
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }

# Hilt
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }

# Google Services
google-services = { id = "com.google.gms.google-services", version.ref = "googleServices" }

# Firebase
firebase-crashlytics = { id = "com.google.firebase.crashlytics", version = "2.9.9" }
firebase-perf = { id = "com.google.firebase.firebase-perf", version = "1.4.2" }

# OpenAPI
openapi-generator = { id = "org.openapi.generator", version = "7.1.0" }

# Gradle toolchains resolver
gradle-toolchains-foojay-resolver = { id = "org.gradle.toolchains.foojay-resolver-convention", version = "1.0.0" }

[bundles]
compose = [
    "androidxUi",
    "androidxUiGraphics",
    "androidxUiToolingPreview",
    "androidxMaterial3",
    "androidxWindow",
    "androidxActivityCompose",
    "androidxNavigationCompose",
    "androidxLifecycleViewmodelCompose",
    "androidxLifecycleRuntimeCompose"
]
