name: Build and Generate OpenAPI APK

on:
  workflow_dispatch:

jobs:
  build-apk:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 24
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '24'

    - name: Ensure Gradle wrapper exists
      run: |
        if [ ! -f ./gradlew ]; then
          gradle wrapper
        fi

    - name: Zero out OpenAPI generated files
      run: |
        rm -rf <openapi_generated_path>/* || true

    - name: Generate OpenAPI code
      run: ./gradlew <openapi_codegen_command>

    - name: Assemble APK
      run: ./gradlew assembleRelease

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: APK
        path: app/build/outputs/apk/release/*.apk

